### ISSUE TITLE
More array and hash methods

### ISSUE THREAD

**Issue by jordanmaguire** [stephaniewillhide/book_land#46]
You'll need to add a `date_of_birth` attribute to Author, and a `published_at` date to Book in preparation.

1. `Author#zodiac`

That's right, it's happening. I want this method to return the name of the zodiac for an Author based on their `date_of_birth`. There's a lot of fun to be had here, which we can discuss later.

2. `Author#age_at_first_release`

Return a string representing the number of years and days between the Author's date_of_birth and the published_at of their first Book.

The string should look like "x years y days" EG: "27 years 184 days"

3. Implement your own version of to_sentence

**Comment by stephaniewillhide** [comment]
Aries ♈️: March 21 - April 19
Taurus ♉️: April 20 - May 20
Gemini ♊️: May 21 - June 20
Cancer ♋️: June 21 - July 22
Leo ♌️: July 23 - August 22
Virgo ♍️: August 23 - September 22
Libra ♎️: September 23 - October 22
Scorpio ♏️: October 23 - November 21
Sagittarius ♐️: November 22 - December 21
Capricorn ♑️: December 22 - January 19
Aquarius ♒️: January 20 - February 18
Pisces ♓️: February 19 - March 20
