### ISSUE TITLE
Admins can upload a book cover

### ISSUE THREAD

**Issue by jordanmaguire** [stephaniewillhide/book_land#8]
```
Given there is a book "Book A"
When I visit the edit page for "Book A"
Then I can upload a cover for "Book A"
```

Rails uses [ActiveStorage](https://guides.rubyonrails.org/active_storage_overview.html) to support file uploads.

Follow this guide to allow users to upload a cover for a Book.

If you're feeling adventurous, you can use [this library](https://github.com/marinosoftware/active_storage_drag_and_drop) to allow drag and dropping of files to upload the cover.

Later we'll use this image on the front page of the app to show a carousel of books.

**Comment by stephaniewillhide** [comment]
Fixed in #12
